### ISSUE TITLE
GPL is incompatible with the App Store’s Terms and Conditions

### ISSUE THREAD

**Issue by danyowdee** [insurgentgames/Alphabet-Blocks#2]
There’s an article by the Free Software Foundation as to where, what, and why the GPL is in conflict with Apple’s T&C:
http://www.fsf.org/news/blogs/licensing/more-about-the-app-store-gpl-enforcement

While the article is a bit dated, and it focuses on version 2 of the GPL, the conflicting statements remain in GPLv3, (which is even stricter in its formulation of copyleft) and the App Store T&C.

Because the GPL does not allow overriding its copyleft, your addition that one might use the code in App Store Apps is moot. So you’re basically left with any combination of the following options:
- Pull _your own App_ from the Store, because you cannot comply with the license you’ve chosen for your own code. (Probably the last thing you want…)
- Switch to a liberal open source license (like MIT, BSD, etc.).
- Dual license your code. (Then again: why keeping the GPL at all, if one always needed the other license to do something with the code, anyways?)
- Try petitioning Apple to create a DRM-free section on the App Store, or an alternate distribution channel (perhaps similar to Gatekeeper on OS X) for apps that cannot comply with the current T&C. (Unlikely to succeed but if it did, it would be great.)

This list is probably incomplete, but hey…

**Comment by micahflee** [comment]
I've already pulled my own apps from the App Store, and I also let my iOS developer account expire. But before I pulled the apps, I was indeed dual-licensing it. The version here that I was releasing on GitHub is licensed as GPL, and the version in the App Store was licensed as proprietary. Since I'm the copyright owner, I'm allowed to license my own code as proprietary and GPL at the same time if I wish.

I don't want to switch to a liberal license. I licensed it as GPL on purpose. People can do plenty with the code now. They can look at it, they can modify it and compile it and run it on their own iOS devices, and learn how to do very basic stuff with cocos2d-iphone and with box2d (Alphabet Blocks isn't the most complicated thing to write), and then they can go forth and write their own iOS games, and license them however they wish.

I think Apple's anti-GPL terms are ridiculous, and one of the several reasons I decided to give up on Apple and their platforms. That said, I actually don't care if people make derivative works and publish them in the App Store, as long as they comply with the GPL (licensing their own code the same way) and are ok with breaking Apple's terms. In other words, if people just pretend that Apple doesn't have horrible anti-freedom policies and treat these projects as they would any other GPL project, I'm fine with that.

**Comment by danyowdee** [comment]
> That said, I actually don't care if people make derivative works and publish them in the App Store, as long as they comply with the GPL

This _is_ the conflict:
The App Store policies forbid certain things that are required to comply with the GPL.

As far as I understand it, it doesn’t really matter, whether or not you care if people broke that part of the GPL, the license itself does—and not in a positive way. And it isn’t that they can choose to not comply with the App Store’s terms: as you know yourself, there is nothing you can do as a developer to keep Apple from imposing DRM on your App as soon as you’ve submitted it to the store. It’s out of your hands entirely.

So it all boils down to the question:
Why GPL if you say you don’t care if people comply with it, for as long as they publish their sources?

Your source is out here anyway, and (at the very least) as long as you don’t remove it from Github it will stay visible (i.e. the learning by example aspect is covered, regardless of any license).
I understand that you want people who derive their work from yours will make their sources available, (to keep the learning by example foundation growing) so BSD, and MIT are out of the question. But if you explicitly say that you are okay if those derivative works are published on the App Store, then GPL just doesn’t seem to fit.

**Comment by micahflee** [comment]
Re-reading the FSF post about the App Store and GPL, it looks like they key part of the GPL is:

"Each time you redistribute the Program (or any work based on the Program), the recipient automatically receives a license from the original licensor to copy, distribute or modify the Program subject to these terms and conditions. **You may not impose any further restrictions on the recipients' exercise of the rights granted herein.**"

I think that that you, the person releasing derivative work, isn't imposing any restrictions. Apple is imposing the restrictions, and therefore Apple is breaking the GPL (which is why they ban GPL apps, so they don't have to break that license). Technically, you and your users need to break Apple's rules for everyone to retain the same rights. But in practice, if you distribute the source code you compiled for your app and include a GPL license with it, everyone gets the same rights in the end.

The problem lies with Apple, not with releasing software as GPL. It sucks for people who aren't ok with advocating breaking Apple's rules though, so I hope that those people decide to stop developing for Apple platforms and start developing for open ones instead.

**Comment by danyowdee** [comment]
The decision of publishing a derivative work through the App Store is an active choice that consists of several steps one has to actively perform. By no means can somebody say “hey I've just put it there for others to get, I don’t care how they're gonna get it”.

When _you_ agree to the App Store’s terms, _you_ agree that Apple does “impose any further restrictions on the recipients’ excercise of the rights [on using your app] granted therein” _on your behalf_, thus whoever submits GPL software to the store violates the license.

The change to the App Store terms which explicitly states that you cannot publish software that is licensed under the GPL, is only a clarification of the legal situation that already existed before. If I remember correctly, it was added in the aftermath of the case in the article to make this conflict explicit.

**Comment by sjatkins2** [comment]
This is nonsense.  I can use GPL software on any computer it is capable of running on.  GPL was intented primarily to prevent someone making the source proprietary or restricted.  It was never ever intended to restrict what sort of computer I could run the software on or in what sort of venue I could offer the running program up.  People are straining at minor technicalities and missing the entire essence.  

Another evidence of this imho is those ugly headers on every single source file in so many FLOSS software sets.  This is not necessary in order for the source to be available.  It is more anal nonsense.

**Comment by danyowdee** [comment]
To be honest, I don’t really know anymore why I opened this issue about 30 months ago.

From where I stand today, I would understand the “License” section of the readme to the effect that this source is not under GPL, but under a modified version of it.
I don’t know if a modification in this form is legally possible or sufficient to be effective. And I don’t really care anymore, so I’m going to close this issue.
(Apparently I did care back then—don’t know why anymore.)

Please allow me a few remarks on your comment regarding the GPL, though:

> I can use GPL software on any computer it is capable of running on.

Correct, but I never argued against that.

> GPL was intented primarily to prevent someone making the source proprietary or restricted.

Yes, that is one of the main objectives of the GPL. It does have a couple of other objectives of similar (if not equal) importance, though.

The following assumes that we are talking about the GPL, not any modified version of it:

> It was never ever intended to restrict what sort of computer I could run the software on or in what sort of venue I could offer the running program up.

The first part is certainly true. However, the latter part is—as far as I can tell—incorrect.

There have been legal disputes over the distribution side of the GPL in the past, and—to the best of my knowledge—all of them where the distributor imposed limitations on the freedoms granted by the GPL (such as e.g. the right to disassemble the software which the App Store terms and conditions clearly deny) the dispute ended in either of the following:
1. the distributor removed the limitations in order to comply with the GPL
2. the distributor had to stop offering the software because they did not comply with the GPL

For this reason, I have to strongly disagree with your assessment:
The rules that the GPL defines for the distribution of software covered by that license are **not** a <q>minor technicalit[y]</q>. They are a core aspect of the GPL.

It is true:
Everyone can take any source code covered by the GPL tweak it, compile it, and (given they have a valid development certificate and the code signing gods are friendly) install that or any derivative work they created on their registered devices.
What you can **not** do, however, is create an app based on GPL licensed code and submit that to the App Store. And that is because of the clash of these rules in the GPL and the App Store terms and conditions.
